-- Idempotent starter catalog: 25 cultural properties on UNESCO's World Heritage List.
-- Coordinates and media URLs are intentionally NULL/absent pending verification/licensing.
-- All descriptions are concise paraphrases of the linked UNESCO World Heritage Centre record.

INSERT INTO heritage_categories (name, slug) VALUES
  ('Cave and rock-cut site', 'cave-rock-cut'),
  ('Temple and religious site', 'temple-religious'),
  ('Fort and palace', 'fort-palace'),
  ('Archaeological site', 'archaeological'),
  ('Historic urban ensemble', 'historic-urban'),
  ('Stepwell and water heritage', 'water-heritage'),
  ('Scientific heritage', 'scientific')
ON CONFLICT (slug) DO NOTHING;

WITH seed(slug,name,description,history,cultural_significance,architecture,historical_period,category_slug,state,district,unesco_id,inscription_year) AS (VALUES
('agra-fort','Agra Fort','A Mughal citadel containing palaces, audience halls and mosques within red sandstone walls.','A major Mughal imperial fortress developed from the 16th century, with notable additions under Shah Jahan.','The fort and nearby Taj Mahal together express the scale and artistic achievement of Mughal rule.','Red sandstone enclosure with palaces including Jahangir Palace and Khas Mahal, audience halls and mosques.','Mughal period, 16th–17th centuries','fort-palace','Uttar Pradesh','Agra','251',1983),
('ajanta-caves','Ajanta Caves','A group of Buddhist cave monuments with monasteries, worship spaces and mural paintings.','The caves were created in phases from the 2nd century BCE through the later ancient period.','The paintings and sculpture are major records of Buddhist art and religious life in ancient India.','Rock-cut chaityas and viharas with sculpted facades and painted interiors.','2nd century BCE–5th century CE','cave-rock-cut','Maharashtra','Chhatrapati Sambhajinagar','242',1983),
('ellora-caves','Ellora Caves','A large sequence of Buddhist, Hindu and Jain cave monuments cut into a basalt escarpment.','The caves were created over several centuries in the first millennium CE.','The site illustrates the coexistence and artistic expression of multiple religious traditions.','Rock-cut monasteries, temples, sculptures and the monumental Kailasa temple.','6th–10th centuries CE','cave-rock-cut','Maharashtra','Chhatrapati Sambhajinagar','243',1983),
('taj-mahal','Taj Mahal','A white marble mausoleum set within a formal garden complex on the Yamuna.','Commissioned by Mughal emperor Shah Jahan; construction of the mausoleum ran from 1632 to 1648, with associated works completed later.','It is recognized as a major work of Indo-Islamic sepulchral architecture and craftsmanship.','Symmetrical marble mausoleum, dome, minarets, mosque, guest house and garden; inlaid stone decoration.','Mughal period, 17th century','fort-palace','Uttar Pradesh','Agra','252',1983),
('mahabalipuram-monuments','Group of Monuments at Mahabalipuram','A coastal ensemble of rock-cut caves, sculpted reliefs, monolithic structures and temples.','The monuments were developed under the Pallava dynasty, especially during the 7th and 8th centuries.','The site records experimentation in South Indian rock-cut and structural temple forms.','Rathas, mandapas, cave sanctuaries, bas-reliefs and structural temples in stone.','Pallava period, 7th–8th centuries','temple-religious','Tamil Nadu','Chengalpattu','249',1984),
('konark-sun-temple','Sun Temple, Konarak','A monumental temple dedicated to the Sun, conceived in the form of a celestial chariot.','Built under the Eastern Ganga ruler Narasimhadeva I in the 13th century.','Its sculptural program and temple form are notable achievements of Kalinga-era art.','Stone chariot form with carved wheels, horses, sculptures and surviving temple structures.','Eastern Ganga period, 13th century','temple-religious','Odisha','Puri','246',1984),
('fatehpur-sikri','Fatehpur Sikri','A planned Mughal city with palaces, religious buildings, public spaces and gateways.','Built as an imperial capital under Akbar between 1571 and 1585.','The city is an exceptional record of Mughal civilization and influenced later Mughal town planning.','Red sandstone ensemble combining palace, administrative and religious architecture.','Mughal period, 16th century','fort-palace','Uttar Pradesh','Agra','255',1986),
('hampi','Group of Monuments at Hampi','The archaeological remains of Vijayanagara’s capital in a distinctive boulder-strewn landscape.','Hampi served as the Vijayanagara capital; the city was devastated after the Battle of Talikota in 1565.','Its remains document a powerful South Indian kingdom and a sophisticated urban and sacred landscape.','Temples, royal and civic structures, market streets, irrigation works and fortifications.','Vijayanagara period, 14th–16th centuries','archaeological','Karnataka','Vijayanagara','241',1986),
('khajuraho-monuments','Khajuraho Group of Monuments','A group of Hindu and Jain temples known for their sculptural programs.','The temples were built chiefly during the Chandella period between the 10th and 11th centuries.','The group represents the artistic and religious culture of the Chandella dynasty.','Stone temples with elevated platforms, towers, sculpted exterior bands and sanctums.','Chandella period, 10th–11th centuries','temple-religious','Madhya Pradesh','Chhatarpur','240',1986),
('elephanta-caves','Elephanta Caves','Rock-cut cave temples and sculptural works on Elephanta Island near Mumbai.','The principal cave complex developed in the first millennium CE; the island also contains older and later archaeological remains.','The site is a major expression of Hindu Shaiva art in a rock-cut setting.','Monolithic cave temples with sanctum, mandapa, pillars and monumental sculpture.','Early medieval period, circa 5th–6th centuries','cave-rock-cut','Maharashtra','Mumbai Suburban','244',1987),
('great-living-chola-temples','Great Living Chola Temples','A group of major Chola temples that remain active places of worship.','The constituent temples were built by Chola rulers between the 11th and 12th centuries, with later additions.','They preserve Chola achievement in architecture, sculpture, painting and bronze casting.','Dravidian temple complexes with vimanas, sanctums, sculptural programs and associated shrines.','Chola period, 11th–12th centuries','temple-religious','Tamil Nadu','Thanjavur / Ariyalur','250',1987),
('pattadakal-monuments','Group of Monuments at Pattadakal','A group of Hindu and Jain temples on the Malaprabha River.','The temples were constructed mainly in the 7th and 8th centuries under the Early Chalukyas.','The group demonstrates the interaction of northern and southern Indian architectural forms.','Temple ensemble combining Nagara and Dravida forms, with carved stone reliefs.','Early Chalukya period, 7th–8th centuries','temple-religious','Karnataka','Bagalkot','239',1987),
('sanchi-buddhist-monuments','Buddhist Monuments at Sanchi','A group of Buddhist monuments on a hill, including stupas, temples, monasteries and pillars.','The earliest monuments date to the Mauryan period; the site developed through later centuries.','The site preserves important evidence of Buddhist architecture and aniconic art.','Stupas with carved gateways, monolithic pillars, sanctuaries and viharas.','3rd century BCE onward','temple-religious','Madhya Pradesh','Raisen','524',1989),
('humayuns-tomb','Humayun’s Tomb, Delhi','A Mughal garden-tomb complex in Delhi.','Built in the 16th century for the Mughal emperor Humayun.','It is an early major example of the dynastic Mughal tomb tradition in India.','Mausoleum set in a garden, with a high platform, central dome and subsidiary structures.','Mughal period, 16th century','fort-palace','Delhi','New Delhi','232',1993),
('qutb-minar','Qutb Minar and its Monuments, Delhi','An archaeological ensemble centered on the Qutb Minar and surrounding monuments.','The complex developed from the early 13th century as new Islamic rulers established power in northern India.','The ensemble testifies to significant architectural and artistic developments in the early Sultanate period.','Tapering red sandstone and marble minar, mosques, gateways, tombs and other structures.','Delhi Sultanate, 12th–14th centuries','archaeological','Delhi','South Delhi','233',1993),
('mahabodhi-temple','Mahabodhi Temple Complex at Bodh Gaya','A Buddhist sacred complex associated with the Buddha’s enlightenment.','The site has been a place of worship since antiquity; Emperor Ashoka is associated with an early temple and commemorative works.','It marks a foundational event in Buddhist religious history and remains a major pilgrimage destination.','Brick temple, shrine structures, votive stupas and the sacred Bodhi tree setting.','Ancient origins; surviving temple largely 5th–6th centuries CE','temple-religious','Bihar','Gaya','1056',2002),
('bhimbetka-rock-shelters','Rock Shelters of Bhimbetka','A landscape of rock shelters containing prehistoric paintings and archaeological evidence.','The shelters preserve evidence of human occupation across a very long span of prehistory and history.','The paintings and habitation traces document changing human life and artistic expression.','Natural sandstone shelters with painted surfaces and archaeological deposits.','Prehistoric to historic periods','cave-rock-cut','Madhya Pradesh','Raisen','925',2003),
('champaner-pavagadh','Champaner-Pavagadh Archaeological Park','A cultural landscape containing archaeological, religious and architectural remains.','The remains include a pre-Mughal Islamic city and monuments developed over multiple periods.','It is recognized as a substantially preserved pre-Mughal city within a wider cultural landscape.','Fortifications, mosques, palaces, temples, water structures and settlement remains.','Early historic through Mughal periods','archaeological','Gujarat','Panchmahal','1101',2004),
('red-fort','Red Fort Complex','A Mughal palace-fort complex in the historic center of Delhi.','Built under Shah Jahan in the 17th century as the palace fort of the Mughal capital.','The complex is associated with Mughal sovereignty and later phases of India’s history.','Red sandstone fortifications enclose palace pavilions, halls, gardens and water features.','Mughal period, 17th century','fort-palace','Delhi','Central Delhi','231',2007),
('jantar-mantar-jaipur','The Jantar Mantar, Jaipur','An astronomical observation site with monumental instruments.','Constructed in the early 18th century under Sawai Jai Singh II.','The observatory reflects a synthesis of astronomical knowledge and architectural design.','Masonry and metal instruments designed for observing celestial positions and measuring time.','Early 18th century','scientific','Rajasthan','Jaipur','1338',2010),
('rani-ki-vav','Rani-ki-Vav (the Queen’s Stepwell) at Patan, Gujarat','A subterranean stepwell designed as both a water structure and a richly decorated monument.','Built in the 11th century and later silted over before rediscovery.','It demonstrates the importance of water management and the high artistic ambition of stepwell design.','Multi-storeyed stepwell with stairways, galleries, pillars and extensive sculpture.','Solanki period, 11th century','water-heritage','Gujarat','Patan','922',2014),
('nalanda-mahavihara','Archaeological Site of Nalanda Mahavihara at Nalanda, Bihar','The archaeological remains of a major Buddhist monastic and scholastic institution.','Nalanda developed as a center of learning in ancient and early medieval India and ceased functioning as an institution in the 13th century.','Its organization and pedagogy influenced later Buddhist institutions across Asia.','Monasteries, shrines, stupas and associated structures arranged across an extensive site.','5th–13th centuries CE','archaeological','Bihar','Nalanda','1502',2016),
('historic-city-ahmadabad','Historic City of Ahmadabad','A historic walled city with traditional neighborhoods, religious buildings and civic spaces.','Founded in the 15th century, the city developed under successive regional and imperial powers.','Its urban form reflects cultural exchange and a living tradition of community-based neighborhoods.','Fortified city fabric, pols, timber houses, gates, mosques and temples.','Sultanate period onward, 15th century','historic-urban','Gujarat','Ahmedabad','1551',2017),
('mumbai-victorian-art-deco','Victorian Gothic and Art Deco Ensembles of Mumbai','An urban ensemble of 19th-century Victorian Gothic and 20th-century Art Deco buildings.','The ensembles developed as Mumbai expanded as a major colonial-era port and city.','They show how global architectural styles were adapted to local conditions and urban life.','Public buildings and residential blocks around open spaces, including Gothic Revival and Art Deco forms.','19th–20th centuries','historic-urban','Maharashtra','Mumbai City','1480',2018),
('dholavira','Dholavira: a Harappan City','An archaeological city of the Indus Civilization on Khadir Island in Gujarat.','The settlement flourished during the third and second millennia BCE.','It provides evidence of Harappan urban planning, water management and craft production.','Planned city divisions, stone masonry, reservoirs, drains and carefully aligned structures.','Harappan period, 3rd–2nd millennia BCE','archaeological','Gujarat','Kutch','1645',2021)
)
INSERT INTO heritage (name,slug,description,history,cultural_significance,architecture,historical_period,category_id,state,district,latitude,longitude,publication_status)
SELECT s.name,s.slug,s.description,s.history,s.cultural_significance,s.architecture,s.historical_period,c.id,s.state,s.district,NULL,NULL,'published'
FROM seed s JOIN heritage_categories c ON c.slug=s.category_slug
ON CONFLICT (slug) DO NOTHING;

WITH seed(slug,unesco_id,inscription_year) AS (VALUES
('agra-fort','251',1983),('ajanta-caves','242',1983),('ellora-caves','243',1983),('taj-mahal','252',1983),('mahabalipuram-monuments','249',1984),('konark-sun-temple','246',1984),('fatehpur-sikri','255',1986),('hampi','241',1986),('khajuraho-monuments','240',1986),('elephanta-caves','244',1987),('great-living-chola-temples','250',1987),('pattadakal-monuments','239',1987),('sanchi-buddhist-monuments','524',1989),('humayuns-tomb','232',1993),('qutb-minar','233',1993),('mahabodhi-temple','1056',2002),('bhimbetka-rock-shelters','925',2003),('champaner-pavagadh','1101',2004),('red-fort','231',2007),('jantar-mantar-jaipur','1338',2010),('rani-ki-vav','922',2014),('nalanda-mahavihara','1502',2016),('historic-city-ahmadabad','1551',2017),('mumbai-victorian-art-deco','1480',2018),('dholavira','1645',2021)
)
INSERT INTO heritage_sources (heritage_id,source_name,source_url,source_note)
SELECT h.id,'UNESCO World Heritage Centre', 'https://whc.unesco.org/en/list/' || s.unesco_id,
       'Official property record; seed text is a concise paraphrase. Coordinates and image assets are intentionally not seeded.'
FROM seed s JOIN heritage h ON h.slug=s.slug
ON CONFLICT (heritage_id,source_url) DO NOTHING;

WITH seed(slug,unesco_id,inscription_year) AS (VALUES
('agra-fort','251',1983),('ajanta-caves','242',1983),('ellora-caves','243',1983),('taj-mahal','252',1983),('mahabalipuram-monuments','249',1984),('konark-sun-temple','246',1984),('fatehpur-sikri','255',1986),('hampi','241',1986),('khajuraho-monuments','240',1986),('elephanta-caves','244',1987),('great-living-chola-temples','250',1987),('pattadakal-monuments','239',1987),('sanchi-buddhist-monuments','524',1989),('humayuns-tomb','232',1993),('qutb-minar','233',1993),('mahabodhi-temple','1056',2002),('bhimbetka-rock-shelters','925',2003),('champaner-pavagadh','1101',2004),('red-fort','231',2007),('jantar-mantar-jaipur','1338',2010),('rani-ki-vav','922',2014),('nalanda-mahavihara','1502',2016),('historic-city-ahmadabad','1551',2017),('mumbai-victorian-art-deco','1480',2018),('dholavira','1645',2021)
)
INSERT INTO heritage_timeline_events(heritage_id,title,description,event_period,event_date,display_order,source_id)
SELECT h.id,'Inscribed on UNESCO World Heritage List','The property was inscribed on UNESCO’s World Heritage List.',s.inscription_year::text || ' CE',NULL,1,src.id
FROM seed s JOIN heritage h ON h.slug=s.slug
JOIN heritage_sources src ON src.heritage_id=h.id AND src.source_url='https://whc.unesco.org/en/list/' || s.unesco_id
WHERE NOT EXISTS (SELECT 1 FROM heritage_timeline_events e WHERE e.heritage_id=h.id AND e.title='Inscribed on UNESCO World Heritage List');

